### ISSUE TITLE
Yellow border on the side of tutorial screen after swipe it!

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#1]
<h2>Steps:</h2>
1. Open the app for the first.
2. Tap on the tutorial button on the bottom-right or swipe left.
3. Keep swiping left!

<h2>The result:</h2>

The last screen (Lifetime Support) could be swiped to the left still, when the user swipe it left, it will pull a yellow colored screen. When the user let it go, The yellow screen will not hide completely.
There will be a yellow border on the right side.

![evernote camera roll 20160112 173740](https://cloud.githubusercontent.com/assets/13262511/12282867/7740fc04-b956-11e5-880e-36ce0cdbf8f7.png)

<h2>Expectation:</h2>

The last page of the tutorial (Lifetime Support) should be fixed (No more swipe to the left).

![evernote camera roll 20160112 173710](https://cloud.githubusercontent.com/assets/13262511/12282837/48dc028c-b956-11e5-80a4-10da2b4fd7d0.png)

<b>Thank you
Wameedh</b>

**Comment by imougy** [comment]
This is a third party component and I agree with your observation, however, given the list to do on my side, I will defer this one.
