### ISSUE TITLE
Tapping on Statusbar dose not scroll the UITableView.

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#10]
**Steps:**
1. Go to any company.
2. Choose Earnings view.
3. Make sure that company have more items than the height of the Phone.
4. Swipe up and down.
5. Tabbing on Statusbar does scroll the TableView.
6. Go to Advanced Chart.
7. Go to Earning view. 
8. Tab at the top does not work. 
**The result:**
**.** Tapping on the Statusbar does not scroll.
![image](https://cloud.githubusercontent.com/assets/14064413/12375745/edabb806-bc86-11e5-9c60-62b22f90fac7.png)

**Expectation:**
**.**Tapping on Statusbar should scroll up.

**Comment by imougy** [comment]
Thank you for the issue. I have fixed it in 5.5
