### ISSUE TITLE
The Icons color are not visible to read  

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#12]
**Steps:**
**1.** Go to Portfolios view.
**2.** Tap on the tutorial button on the bottom-right.
**3.** Try to send an email by the**"Help/Support"**  or try to backup by the **"Back Up Portfolios"**.
**Results:**
**.** The color Icons on TableView are not visible. 
**.** On the top of the TableView **Cancel** and **Send** are dark.
![image](https://cloud.githubusercontent.com/assets/14064413/12377044/5c58de3c-bcc3-11e5-9322-3edbcfa56bf8.png)
![image](https://cloud.githubusercontent.com/assets/14064413/12377046/6a3f6c64-bcc3-11e5-8369-684a3d7c1753.png)
**Expectation:**
**.** Seeing any Icon and reading any Icon should easy inside the App.

**Comment by imougy** [comment]
I fixed this in version 5.5.11. It is not out yet, but soon.
