### ISSUE TITLE
Buying and selling a position is not easy.

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#13]
**Steps:**
**1.** Make sure you have positions in the Position box.
**2.** To sell a position, you need to select it, then tap on the delete button.

**Results:**
**.** Users are confused and don't know that selling requires delete.

![image](https://cloud.githubusercontent.com/assets/14064413/12399783/db124cc8-bdd0-11e5-9905-6bbc88d6e698.png)

**Expectation:**

**.** We need to make it obvious to sell a position. Maybe when you select a position, an action sheet pops up with menu items like (Sell All, Sell Partial, Buy More, etc...).

**Suggestion:** 
**.** Having an action sheet displays a set of choices related to a task it helps a lot.

**Comment by imougy** [comment]
I added several command to Close/Close All/Reduce of the positions.
Thanks,
