### ISSUE TITLE
Missing a cursor in Position box

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#14]
**Steps:**
**1.** Go to Portfolios tap.
**2.** Try to have positions in the Position box.
**Results:**
**.** Anywhere tabbing in the Positions box, we can write any position we need.
![image](https://cloud.githubusercontent.com/assets/14064413/12410103/577da762-be26-11e5-9eb9-7da3f08a8323.png)
**Expectation:**
**.**  need to make it obvious to see a cursor in the Position box.
**Suggestion:**
It’s often said that people spend no more than a minute or two evaluating a new app.

**Comment by imougy** [comment]
Not a valid bug.
