### ISSUE TITLE
Need to add total change to the allocation view

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#15]
**Steps:**
**1.** Go to Portfolios tab.
**2.** The Allocation view is missing the Total Change.
**Results:**
- It shows daily and total for individual stocks but only daily for the whole portfolio.

**Suggestions:**
- We need to see the Total Change for the entire portfolio.

**Comment by imougy** [comment]
Great, I added it. Please look below:-
![image](https://cloud.githubusercontent.com/assets/3361440/12441602/ab25fffe-befd-11e5-91ff-45bd42f7c5ac.png)
