### ISSUE TITLE
In the pie Chart Zoom Dialog  the table Header Control is not sync with Segmented Control.

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#16]
**Steps:**
**1.** Go to Portfolios tab.
**2.** Tap on any Pie Chart to zoom.
**3.** Make sure the Segmented Control is switched to Change %.
**4.** Close the Dialog.
 **5.** Tap on the Pie Chart. 

**Result:**
- The table header is Weight.
  ![image](https://cloud.githubusercontent.com/assets/14064413/12442546/ac5c5cf8-bf05-11e5-94bd-70d0baa4ec18.png)

**Expectation:**
- The Table Header should show Change% view.

**Comment by imougy** [comment]
Fixed in 5.5.15.
Thanks,
