### ISSUE TITLE
In the Pie Chart Dialog Zoom "Weight %" should be "Allocation%"

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#17]
**Steps:**
**1.** Go to Portfolios tab.
**2.** In the Allocation view tap on any Pie Chart Zoom.
**Result:**
- In the Segmented Control we have two options, Weight% and Change%.

**Expectation:**
- "Weight %" should be "Allocation %".

**Comment by imougy** [comment]
Fixed in version 5.5.10
