### ISSUE TITLE
Missing two Arrows indicated for Total Change and Daily Change 

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#18]
**Steps:**
**1.** Go to Portfolios tab then Allocation view.
**2.** Look at Total Change number and also Daily Change number.

**Result:**
-  We only see one Arrow near to Total Account Value number.

**Exception:**
- Should have Arrows indicated  for Total Change and Daily Change up/down.
  ![image](https://cloud.githubusercontent.com/assets/14064413/12462955/f5f1dcba-bf75-11e5-8c35-43c42e966403.png)

**Comment by imougy** [comment]
Thanks, fixed in build 5.5.3.
