### ISSUE TITLE
The Position Tutorial View Goes Black!

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#2]
<h2>Steps:</h2>

1.Open the app.
2. Search for a stock.
3. Tap on the name of the stock you want.
4. Tap on the menu icon on the top-right .
5. From the menu, tap on "Add to portfolio" and choose a portfolio.
6. Edit portfolio view will comes, tap on Position Tutorial's icon on the top-right of the current position view.
7. Swipe up and down. 

![evernote camera roll 20160112 152020](https://cloud.githubusercontent.com/assets/13262511/12283947/67624b76-b960-11e5-8b55-df0a1d03d09f.png)

<br><br><br>
![evernote camera roll 20160112 151200](https://cloud.githubusercontent.com/assets/13262511/12283951/779c6e40-b960-11e5-8403-32cace4f1e99.png)

<br><br>

<h2>The result:</h2>

<b>The Position Tutorial view goes black.</b>

![evernote camera roll 20160112 151200-2](https://cloud.githubusercontent.com/assets/13262511/12283975/ac4dd20a-b960-11e5-8d4e-c0513f339d36.png)

<h2>Exception:</h2>

The edit portfolio view should not be black. The user should be able to edit and leave the view smoothly.

![img_1125](https://cloud.githubusercontent.com/assets/13262511/12284213/e54cb114-b962-11e5-88e5-be52198fbf9f.PNG)

**Comment by imougy** [comment]
Awesome bug.
Will take a look.

**Comment by imougy** [comment]
Fixed in latest beta. Thanks for the heads up!

**Comment by imougy** [comment]
Please close if confirmed.
