### ISSUE TITLE
Add Split command in the Portfolio Menu. 

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#22]
**Steps:**
**1.** Open the App and to go Portfolios tab.
**2.** When a stock splits, the only way for users to handle this is by going to each holding and changing the price and quantity.

**Expectations:**
- One command that allows users to specify the split factor. 
- The App then will go through all the holdings and adjust the purchase price and the quantity purchased.

**Suggestion:**
- Add Split command in the Portfolio Menu.

**Comment by imougy** [comment]
Done, please test it. You can find it in the main Portfolio tab.
