### ISSUE TITLE
A crash in version 5.5.7 regarding the Add new position

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#23]
**Steps:**
1. Go to Portfolios tab.
2. Tap on the top-left  to open a page for adding New Portfolio.
3.  In Current Positions box tap on the "Add" button. 
**Results:**
- When we tap on Add, the app crashes.
  ![image](https://cloud.githubusercontent.com/assets/14064413/12603839/f72e8480-c46a-11e5-9f14-fe698656d641.png)

**Expectation:**
- The user should be able to use "Add" without any problem. :)

**Comment by imougy** [comment]
Fixed in 5.5.10
