### ISSUE TITLE
Data doesn’t match Yahoo or Morningstar

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#25]
**Steps:**
**I.** In the Search tab inside App.
**2.** Search QQQX to see a result by Number view.

**Results:**
- A number appear next to Yield division doesn't match with Yahoo Finance and Morningstar.
  ![image](https://cloud.githubusercontent.com/assets/14064413/12632362/3beda780-c50c-11e5-80b6-25bf093eb737.png)

**Yahoo Fainance**
![image](https://cloud.githubusercontent.com/assets/14064413/12632494/37fab860-c50d-11e5-848d-abb49ea776dc.png)

**Morningstar**

![image](https://cloud.githubusercontent.com/assets/14064413/12632565/d6199dd6-c50d-11e5-8747-5efc0640f541.png)

**Expectation:**
- The data shows inside an App should match with original information at any Website we use.

**Comment by imougy** [comment]
Should be fixed now.
Please retest and make sure it is closed.
Thanks,
