### ISSUE TITLE
The switch Auto Update Cash doesn't do any thing to cash

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#28]
**steps**
1. Go to portfolios tab.
2. Tap on the menu top-left "+ "
![image](https://cloud.githubusercontent.com/assets/14064413/12693854/c2454ec4-c6cd-11e5-83c9-5d0bf117ecbe.png)
![image](https://cloud.githubusercontent.com/assets/14064413/12694047/8118e65c-c6d4-11e5-8787-645eca82c874.png)

**Results:**
- The switch Auto Update cash doesn't do anything to the cash when you update positions
  ![image](https://cloud.githubusercontent.com/assets/14064413/12691966/0c86f7da-c6a6-11e5-82dc-a3f7f0187e35.png)
  **Expectations:**
- The Switch Auto Update Cash should work.

**Comment by imougy** [comment]
Fixed in latest update 5.6
