### ISSUE TITLE
Positions of the buttons in the chart view are not good.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#29]
<h2>Steps:</h2>
1. Open the app.
2. Go to Portfolio tab.
3. Got to Numbers.
4. Tap on any sock.
5. Go to Technicals
6. Tap on Zoom

![image](https://cloud.githubusercontent.com/assets/13262511/12699699/f337730c-c779-11e5-9868-e859acdeb004.png)

<h2>Results:</h2>
- When you go to Technicals the zoom button is not visible. There should be a better solution for the UI.
- When you tap on Zoom; the chart will be in zoom mood as you see in image below the share button is over another item in the chart!

![image](https://cloud.githubusercontent.com/assets/13262511/12699701/245a84ec-c77a-11e5-95ff-93f021403615.png)

<h2>Expectation:</h2>
- For the Zoom button I would suggest a tab bar with (more) tab.
- For the share button I think there is a space to bring to the right as you see in the image.

Thank you :)
Wameedh

**Comment by imougy** [comment]
I fixed the one in the technical chart. The one in the advanced view is kind of hard as I don't know where to put them.
I will close it and leave it as is.
