### ISSUE TITLE
Advance chart view goes messy and the indicators view is not friendly.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#3]
<h2>Steps:</h2>
1. Open the app.
2. Portfolios then choose any portfolio by tapping on it.
3. Charts, tap on any chart to open it
4. Tap on the Indicators icon on the top-mid of the chart
5. Scrolling on the indicators.
6. Close the indicators view.

![evernote camera roll 20160112 230719](https://cloud.githubusercontent.com/assets/13262511/12318329/49153586-ba4e-11e5-84f7-43767729da41.png)

<h2>Result:</h2>
- When you scroll up and down on the indicators view, it doesn't scroll smoothly. Sometimes if you are scrolling up or down and your finger mistakenly grab the top of the indicators view, the whole view will move.
- After closing the indicators view the chart become messy.

![evernote camera roll 20160112 230445](https://cloud.githubusercontent.com/assets/13262511/12318336/504242f4-ba4e-11e5-8270-c6d25c31351d.png)

<h2>Expectation: </h2>
- The indicators view should be easy and smooth while interacting with it.
- The chart should looks fine after closing the indicators view.

**Comment by imougy** [comment]
Thanks for the bug. Now this is [duplicate](https://github.com/imougy/TradingView/issues/6) in the Trading View Github.
