### ISSUE TITLE
Missing character "@" with keyboard while editing any positions.

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#31]
**Steps:**
1. Go to portfolios Tab.
2. Try to add a new Position.
3. Look at the keyboard appear.

![image](https://cloud.githubusercontent.com/assets/14064413/12709269/0de2ba32-c85f-11e5-8c9d-87c46b401bcc.png)
**Result:**
- The keyboard that appears is the "default" keyboard and you need to tap on the "shift" key to see the "@" character.

**Expectation:**
- While editing any positions, the keyboard that appears needs to be similar to the keyboard that appears when you tweet, because the handy  existence of character "@".
  ![image](https://cloud.githubusercontent.com/assets/14064413/12709244/9e4bc97a-c85e-11e5-8d5f-debd6002e158.png)

**Comment by imougy** [comment]
Fixed in 5.5.15 (next update).
