### ISSUE TITLE
The Icon in Apple Watch looks isn't the same as iPhone.

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#35]
New Version with new Icon for Stocks Live
.
**Result**
The Icon in Apple Watch looks isn't the same as iPhone.

**Expectation**
. It should see all the icons in iPhon and Appl Watch and iPad the same.

**Comment by imougy** [comment]
Fixed in latest build 5.6.

**Comment by imougy** [comment]
![watchnotification 2x](https://cloud.githubusercontent.com/assets/3361440/13058174/4dd7b8d6-d3d6-11e5-9144-951308125eb5.png)
