### ISSUE TITLE
The setting change automatic

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#4]
**Steps:**

```
 1. After opening the App.
 2. Go to the settings inside the App.
 3. Try to turn "on" Prevent Auto-Lock.
 4. Go back and check the setting you already changed. 
```

![image](https://cloud.githubusercontent.com/assets/14064413/12336218/368d3da4-bab8-11e5-8f9d-74e45c76024d.png)

![image](https://cloud.githubusercontent.com/assets/14064413/12336339/edd63a1a-bab8-11e5-878a-d786910726db.png)

**The result:**

You will see Prevent Auto-Lock changing back.

![image](https://cloud.githubusercontent.com/assets/14064413/12336294/a6950398-bab8-11e5-9c6a-5eccdd0bae17.png)

 **Expectation:**

  The setting from the App should not change.

**Comment by imougy** [comment]
Fixed in 5.4.
Thanks
