### ISSUE TITLE
Stock Live won't launch!

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#42]
<h2>Steps:</h2>

1- Open the Stocks Tape app.
2- Tap on any tape.
3- Tap on Launch Stock Live.

![image](https://cloud.githubusercontent.com/assets/13262511/14769863/477ffed6-0a17-11e6-9134-29bd224dc26e.png)

<h2>Results:</h2>

Stock Live won't launch!

<h2>Expectation:</h2>

Stock Live must launch.

**Comment by imougy** [comment]
Nice bug.1.5.3
Please test in the next release
