### ISSUE TITLE
The UI/UX of the stock chart view.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#43]
<h2>Steps:</h2>

1- Open the Stocks Tape app.
2- Tap on any tape.
3- Tap on the arrows on the bottom left or right.

![image2](https://cloud.githubusercontent.com/assets/13262511/14770009/1e6da47c-0a1b-11e6-9b30-949e04014b45.png)

<h2>Results:</h2>

The stock name on the top will change when the user taps on the arrows. This is cool. I like being able to go to the next or prevues stock easy like that, but the UX needs to be improved as follow under expectation

<h2>Expectation:</h2>

When the user tap on the arrow he/she will expect that the title between the arrows is what is going to change, while here when the user tap on the arrow the title on the top will change (the stock name).

The arrow should move to the top. The name of the stock will be between the arrows. This will match the user expectation when he/she tap on the arrows.

Also, if the user can swipe to switch to the next or prevues stock that will be a good user experience.

**Comment by imougy** [comment]
Good point.
However, I will leave that the bottom are buttons that you can tap to do something, the top is information.
I like the swipe idea, but again, no time. Good suggestions.
