### ISSUE TITLE
Tutorials won't open!

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#44]
<h2>Steps:</h2>

1- Open the Stocks Tape
2- Go to setting
3- Go to tutorials
4- tap on a tutorial to open.

![31](https://cloud.githubusercontent.com/assets/13262511/14770094/e152dd52-0a1d-11e6-9c42-fd559788c8c2.png)

![32](https://cloud.githubusercontent.com/assets/13262511/14770095/e6c9967c-0a1d-11e6-966e-843e06f8204b.png)

<h2>Results:</h2>

The tutorials won’t open and if the user keeps trying to open any tutorial the app will crash.

<h2>Expectation:</h2>

when the user taps on any tutorial it should open with no issues.

**Comment by imougy** [comment]
You saved my ass.
Thank you!
Fixed in latest release.
