### ISSUE TITLE
A bug in the EVERNOTE icon inside the App.

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#45]
# Steps:

 **1. Open the App.**
 **2. Tap on any stocks in the Activities Tab.** 
 **3. Push on the top  and jump to Notes view.**
![image](https://cloud.githubusercontent.com/assets/14064413/14773648/92b9289c-0a61-11e6-820a-0b135e522b0b.png)

![image](https://cloud.githubusercontent.com/assets/14064413/14773651/9fbd8e34-0a61-11e6-98c8-d0e2159f6ecd.png)

![image](https://cloud.githubusercontent.com/assets/14064413/14773657/b0c86e38-0a61-11e6-926f-895549307c91.png)
# Result:

. You will see a bug after touch on the  elephant Icon in the middle of the page.
 . It does not work as Logo and just a picture 
 . It goes to another page.
# Expectations:

. It supposes a logo just appear in that Area as a logo nothing else.

**Comment by imougy** [comment]
Fixed in latest beta.
Please close if you verify.
Thanks,
