### ISSUE TITLE
Notes are not appearing!

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#46]
<h2>Steps:</h2>

1- Open Stock Live app.
2- Go to any watch list.
3- Tap on any stock (we will pick Facebook stock for this test)
4- From the "Jump to" menu or by swiping left/right got to Notes.
5- Write a note and save it!
6- Close the app and open it again.
7- Go to the Facebook stock an then Notes.
8- Go back to the watch list.
9- Go back to the Facebook stock and then Notes.

![image](https://cloud.githubusercontent.com/assets/13262511/14797043/73b84016-0ae5-11e6-9c02-8761692b4935.png)

<h2>Results</h2>

After doing step 9 the user won't find his/her note.
If the user close and reopen the app she/he will be able to see the note but if he/she do step 8 and 9 then same issue accur.

![image](https://cloud.githubusercontent.com/assets/13262511/14797054/88f12eca-0ae5-11e6-9c71-9ee20d98dc20.png)

<h2>Expectation</h2>

The user should see her/his note!

**Comment by imougy** [comment]
Fixed in latest beta.
Please close if you verify.
Thanks,
