### ISSUE TITLE
NOTE bugs

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#47]
**Steps:**
1. Open the app.
2. Tap on any stocks in Activities tab.
3. Try to make a note for any stocks by Evernote. 
4. leave the page after you save a note and then back.
![image](https://cloud.githubusercontent.com/assets/14064413/14798947/ce39bd40-0aee-11e6-9e5d-adca0d8e02b4.png).

![image](https://cloud.githubusercontent.com/assets/14064413/14798912/ae28d1da-0aee-11e6-913e-dbd2b50cde05.png).

**Result:**
.You couldn't open the note already made it.

**Expectation:**
. The user should  have a chanse to see the note.

**Comment by imougy** [comment]
Fixed in latest beta.
