### ISSUE TITLE
A bug about Evernote screen 

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#48]
**Steps:**
1. Open the app.
2. Search by any Ticker in Search tap.
3. Jump to Notes view.
**Result:** 
. You do not have a full screen like down blow picture.

![image](https://cloud.githubusercontent.com/assets/14064413/14799479/8eb355fc-0af1-11e6-8641-af811feb2a3b.png)

**Expectation:**
. It has to show the icons in the perfect way.

**Comment by imougy** [comment]
Fixed in latest beta.
