### ISSUE TITLE
Data doesn't show in Andrew Keene page

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#50]
**Steps:**
1. Oppen the App.
2. In the Activities Tap.
3. Tab on Andrew Keene. 

**Result:**
 . You couldn't see any data.
 . Like pictures on below. 

![image](https://cloud.githubusercontent.com/assets/14064413/15157682/7f5036b4-16a1-11e6-8be0-b1c09215b077.png)
![image](https://cloud.githubusercontent.com/assets/14064413/15157691/8bac3b6a-16a1-11e6-99c3-4a9c760b8d39.png)
 **Expectation:** 
It should show a date inside that.

**Comment by imougy** [comment]
Nice catch, I will check it.

**Comment by imougy** [comment]
Done
