### ISSUE TITLE
Suggestion to improve the UX for the view setting.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#51]
<h2>Steps:</h2>
- Open the Stocks Tape
- Go to settings

![77](https://cloud.githubusercontent.com/assets/13262511/15337533/2b601f70-1c31-11e6-90da-71b71427871e.png)

<h2>Results:</h2>

The user when he sees “Lock” the next thing he/ she will do is asking “Lock for what?!” then he/she will look at the segments and try to think and conclude this is for the view!

<h2>Expectation:</h2>

We need to give our users the best experience we can give. Changing the “Lock” to “View” and “None” to “Auto” will make it clear for our users that this about how the view will look without extra thinking.

**Comment by imougy** [comment]
I will skip this one, I don't want to put time in it, the app doesn't make much money and no one complained.
Thanks for the reporting though!
