### ISSUE TITLE
Saving a note with picture, audio or chart.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#52]
<h2>Steps:</h2>

1- Open Stock Live app.
2- Go to any watch list.
3- Tap on any stock (we will pick Facebook stock for this test)
4- From the "Jump to" menu or by swiping left/right got to Notes.
5- Make a note with a picture, audio  or a chart !
6- Save the note.

![note1](https://cloud.githubusercontent.com/assets/13262511/15660355/0483e332-2690-11e6-9974-817a0156a42d.png)

![note2](https://cloud.githubusercontent.com/assets/13262511/15660359/08dd879e-2690-11e6-8729-2ea46a8300e8.png)

<h2>Results:</h2>

The note won’t save unless the user wright something along with the picture, audio or the chart.

<h2>Expectation:</h2>

The user should be able to save the note even without a text.

**Comment by imougy** [comment]
Nice catch, will fix.

**Comment by Wameedh** [comment]
Fixed in the new update. :)
