### ISSUE TITLE
The user can’t delete the recorded audio!

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#53]
<h2>Steps:</h2>

1- Open Stock Live app.
2- Go to any watch list.
3- Tap on any stock (we will pick Facebook stock for this test)
4- From the "Jump to" menu or by swiping left/right got to Notes.
5- Make a note an audio!
6- Start recording.
7- delete the recorded audio

![note1](https://cloud.githubusercontent.com/assets/13262511/15660435/590aadea-2691-11e6-9a4a-25f6e1e7e208.png)

![audionote](https://cloud.githubusercontent.com/assets/13262511/15660462/b1f87658-2691-11e6-9385-34955c6f7952.png)

<h2>Results:</h2>

The delete button is not working.

<h2>Expectation:</h2>

The delete button should work.

**Comment by imougy** [comment]
Nice catch!
Will fix next update.
