### ISSUE TITLE
Earnings Surprises Exceeded activity cell shows no data.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#57]
<h2>Steps:</h2>

1- Open Stock Live app.
2- Go to Activities.
3- Scroll down to "Earnings Surprises Exceeded"

<h2>Results:</h2>

 "Earnings Surprises Exceeded" activity is always empty.

![222](https://cloud.githubusercontent.com/assets/13262511/15803475/06b335ce-2a94-11e6-995b-f82f44759ed0.png)

![333](https://cloud.githubusercontent.com/assets/13262511/15803476/0a01c13c-2a94-11e6-81f2-f015eddb980c.png)

<h2>Expectation:</h2>

There should be Data.

**Comment by imougy** [comment]
It depends on the day. You can check the data from here which matches Stocks Live. http://www.nasdaq.com/earnings/daily-earnings-surprise.aspx
