### ISSUE TITLE
Missing the Disclosure indicator row. 

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#58]
**Steps:**
1. Open the App.
2. Tap on Resources tab.
3. Tap on Education Center.

![image](https://cloud.githubusercontent.com/assets/14064413/15847166/986060f0-2c38-11e6-8cf9-03bec0e18a19.png)

**Result:** 

. You will see the collection of video from the different financial adviser.
. If you tap on any adviser names or cell you will see the group of video on next page.
. What it's missing here haveing a Disclosure indicator row. 

![image](https://cloud.githubusercontent.com/assets/14064413/15847533/84e52dfa-2c3b-11e6-8e22-0e0f028df1a0.png)

![image](https://cloud.githubusercontent.com/assets/14064413/15847211/ee8089a6-2c38-11e6-85af-cc2e6b082c60.png)

**Expectation:**
. It good to have a Disclosure indicator row to navigate you with another table associated with the row.

**Comment by imougy** [comment]
Done.
