### ISSUE TITLE
Missing an access to all education video from Activities Tab

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#59]
**Steps:**
1. Open the App.
2. Check Activities.
3. Tap on the plus icon at the top left.
4. Choose Education Center. 
![image](https://cloud.githubusercontent.com/assets/14064413/15872481/8b7d0b74-2cae-11e6-9c41-41b3c3352a49.png)

![image](https://cloud.githubusercontent.com/assets/14064413/15872486/946b9336-2cae-11e6-9090-fbaa1ad06f69.png)

**Result:**

. You will see the names from three different famous financial advisers.

. What we miss here, we couldn't tap on any video and go next page like when you have  
  access to all video from Resources Tab.

![image](https://cloud.githubusercontent.com/assets/14064413/15872568/01d7f8d8-2caf-11e6-87bf-c4aa4b14579a.png)

**Expectation:**
. It's good to have access from Education center tab to see all video.

**Comment by imougy** [comment]
Done.
