### ISSUE TITLE
AirDrop is not functioning

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#6]
**Steps:**
1. Go to Activities tab. 
2. Go to menu then share your Heatmap view. 
3. Choose AirDrop and share it. 

![image](https://cloud.githubusercontent.com/assets/14064413/12347827/7a79e8ec-bb16-11e5-8a7d-f6f4843c6fb4.png)

**Result:**
**.** Error message below . 

![image](https://cloud.githubusercontent.com/assets/14064413/12346974/fe40ecb0-bb0d-11e5-81a6-15fcc7be7742.png)

**Expectation:**
Send a file or any view by AirDrop.

**Comment by imougy** [comment]
I will defer this bug for now. No one ask for it.
