### ISSUE TITLE
bug in Activities it shows a gap.

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#60]
**Steps:**
1. Open the App.
2. In Activities tab.
3. Scroll up and down on the page.

**Result:**
. There is a gap appears without any data.
![image](https://cloud.githubusercontent.com/assets/14064413/15915218/55b8be86-2d9c-11e6-8193-3dfa62d15728.png)

**Expectation:**
. I guess It shouldn't see a gap.

**Comment by imougy** [comment]
Probably this is because the version is 5.6 that doesn't know about the Education Center traders.
