### ISSUE TITLE
Education Center tutorials have no sound.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#61]
<h2>Steps:</h2>

1. Open Stock Live app.
2. Go to Resources.
3. Go to the Education Center.
4. Pick any tutor.
5. Play any video.

![000](https://cloud.githubusercontent.com/assets/13262511/16897551/7b6c3532-4b69-11e6-90cc-c6986c7dd7fe.png)

![0](https://cloud.githubusercontent.com/assets/13262511/16897556/a767f02c-4b69-11e6-9ba9-0b95dc0cc9e0.png)

<h2>Results:</h2>

 There is no voice unless the user uses a headphones.

<h2>Expectation:</h2>

There should be voice with or without using headphones.

**Comment by imougy** [comment]
That I can't reproduce on my device.
Are you sure your Mute button is OFF?

**Comment by Wameedh** [comment]
I just check yeah, looks like because of the Mute button is off!
It is working now!

Regards
Wameedh
