### ISSUE TITLE
Keyboard appears with wrong alignment in the Advanced Chart

### ISSUE THREAD

**Issue by heeva** [imougy/Planet-Earth-Bugs#7]
**Steps:**
1. Go to Advanced Chart.
2. Tap on the Compare icon.
3. Try to write with the keyboard by the Company Comparison search.

![image](https://cloud.githubusercontent.com/assets/14064413/12367027/ed40c274-bb93-11e5-9d75-3eb8f06c3b0b.png)
**Result:**
**.** You will see the way chart works does not look perfect.
![image](https://cloud.githubusercontent.com/assets/14064413/12367004/d03bab6c-bb93-11e5-9ed1-b8ea715182e1.png)
**Expectation:**
**.** The chart should look fine after use keyboard to search.
**.** The Company Comparison view should be easy and smooth while interacting with it.

**Comment by imougy** [comment]
Great bug. I think I will defer this one for now.
