### ISSUE TITLE
Yellow font color on a white background.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#8]
<h2>Steps</h2>
1. Open the app.
2. Got to Watch List tab or Portfolios tab.
3. Selacte any watch list or portfolio by tapping on it.
4. Tap on the slide bar on the top-mid, a menu will appear.

![image](https://cloud.githubusercontent.com/assets/13262511/12364119/a995c0e0-bb81-11e5-8143-599b91639349.png)

<h2>Results:</h2>

Sometimes the color of the font in the menu is yellow on a white background.

![image](https://cloud.githubusercontent.com/assets/13262511/12364166/02d01926-bb82-11e5-998b-88be1629f7e2.png)

![image](https://cloud.githubusercontent.com/assets/13262511/12363990/d509c902-bb80-11e5-9e27-3422b0fc7e3c.png)

<h2>Expectation:</h2>

The font color should be black on a white background.

![image](https://cloud.githubusercontent.com/assets/13262511/12364000/e302d710-bb80-11e5-826f-61085a64a6e9.png)

**Comment by imougy** [comment]
Fixed in 5.4
Thanks,
